sed -i.bak "s/api\/image/static\/images/g" photo_album_1.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_1.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_2.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_2.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_3.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_3.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_4.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_4.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_5.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_5.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_6.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_6.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_7.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_7.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_8.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_8.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_9.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_9.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_10.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_10.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_11.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_11.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_12.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_12.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_13.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_13.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_14.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_14.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_15.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_15.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_16.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_16.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_17.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_17.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_18.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_18.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_19.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_19.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_20.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_20.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_21.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_21.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_22.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_22.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_23.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_23.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_24.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_24.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_25.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_25.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_26.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_26.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_27.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_27.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_28.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_28.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_29.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_29.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_30.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_30.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_31.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_31.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_32.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_32.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_33.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_33.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_34.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_34.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_35.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_35.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_36.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_36.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_37.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_37.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_38.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_38.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_39.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_39.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_40.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_40.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_41.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_41.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_42.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_42.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_43.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_43.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_44.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_44.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_45.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_45.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_46.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_46.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_47.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_47.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_48.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_48.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_49.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_49.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_50.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_50.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_51.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_51.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_52.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_52.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_53.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_53.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_54.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_54.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_55.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_55.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_56.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_56.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_57.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_57.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_58.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_58.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_59.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_59.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_60.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_60.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_61.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_61.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_62.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_62.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_63.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_63.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_64.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_64.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_65.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_65.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_66.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_66.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_67.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_67.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_68.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_68.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_69.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_69.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_70.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_70.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_71.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_71.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_72.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_72.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_73.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_73.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_74.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_74.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_75.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_75.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_76.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_76.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_77.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_77.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_78.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_78.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_79.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_79.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_80.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_80.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_81.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_81.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_82.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_82.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_83.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_83.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_84.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_84.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_85.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_85.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_86.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_86.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_87.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_87.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_88.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_88.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_89.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_89.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_90.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_90.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_91.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_91.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_92.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_92.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_93.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_93.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_94.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_94.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_95.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_95.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_96.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_96.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_97.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_97.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_98.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_98.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_99.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_99.question
sed -i.bak "s/api\/image/static\/images/g" photo_album_100.question
sed -i.bak "s/\/?resize_pix_w=500/.png/g" photo_album_100.question